title: Introduction to Modern Statistics Tutorials
description: Interactive tutorials developed with the learnr package supporting the textbook OpenIntro::Introduction to Modern Statistics Tutorials. 
logo: logo/openintro-hex.png
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jemoji