title: Introduction to Modern Statistics Tutorials (UMCG FORK)
description: UMCG fork of the interactive tutorials of OpenIntro::Introduction to Modern Statistics.
logo: logo/umcg-openintro-hex.png
show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jemoji