title: Introduction to Modern Statistics Tutorials (UMCG FORK)
description: UMCG fork of the interactive tutorials supporting the textbook OpenIntro::Introduction to Modern Statistics Tutorials.
logo: logo/umcg-openintro-hex.png
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jemoji